type ExerciseDataLike = {
  name: string;
  category: string;
  muscleGroup: string;
  equipment: string;
  difficulty: string;
  description: string;
  instructions: string[];
};

type Variant = {
  name: string;
  difficulty?: string;
  descriptionSuffix?: string;
  extraCue?: string;
};

type Template = {
  category: string;
  muscleGroup: string;
  equipment: string;
  difficulty: string;
  description: string;
  instructions: string[];
  variants: Variant[];
};

function buildExercises(templates: Template[]): ExerciseDataLike[] {
  return templates.flatMap((template) =>
    template.variants.map((variant) => ({
      name: variant.name,
      category: template.category,
      muscleGroup: template.muscleGroup,
      equipment: template.equipment,
      difficulty: variant.difficulty ?? template.difficulty,
      description: variant.descriptionSuffix
        ? `${template.description} ${variant.descriptionSuffix}`
        : template.description,
      instructions: variant.extraCue
        ? [...template.instructions, variant.extraCue]
        : template.instructions,
    }))
  );
}

const homeTemplates: Template[] = [
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Sentarse y levantarse con carga ligera para desarrollar fuerza funcional y autonomía diaria.',
    instructions: [
      'Siéntate en una silla o banco estable con una mancuerna junto al pecho',
      'Apoya bien los pies y mantén el torso alto',
      'Ponte de pie empujando el suelo con control',
      'Aprieta glúteos al final del recorrido',
      'Desciende lentamente hasta volver a sentarte',
    ],
    variants: [
      { name: 'Dumbbell Sit-to-Stand' },
      { name: 'Tempo Dumbbell Sit-to-Stand', descriptionSuffix: 'La fase de bajada se hace lenta para mejorar control y tolerancia de esfuerzo.' },
      { name: 'Paused Dumbbell Sit-to-Stand', descriptionSuffix: 'Incluye una breve pausa antes de levantarte para reforzar estabilidad.' },
      { name: 'Alternating Dumbbell Sit-to-Stand Reach', descriptionSuffix: 'Añade un alcance alterno al frente para mejorar coordinación.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Sentadilla a caja con mancuerna para piernas y glúteos con profundidad segura.',
    instructions: [
      'Sostén una mancuerna frente al pecho y colócate delante de una caja o silla',
      'Empuja la cadera hacia atrás hasta tocar suavemente el apoyo',
      'Mantén el pecho alto y las rodillas alineadas',
      'Ponte de pie empujando el suelo con ambos pies',
      'Respira de forma constante durante toda la serie',
    ],
    variants: [
      { name: 'Goblet Box Squat' },
      { name: 'Tempo Goblet Box Squat', descriptionSuffix: 'Usa una bajada lenta para reforzar técnica y control.' },
      { name: 'Paused Goblet Box Squat', descriptionSuffix: 'Incluye una pausa ligera al tocar la caja.' },
      { name: 'Goblet Box Squat to Calf Raise', descriptionSuffix: 'Añade una elevación de talones al final para integrar tobillo y gemelo.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Sentadilla dividida con apoyo externo para reforzar piernas y equilibrio sin impacto.',
    instructions: [
      'Colócate en zancada sujetándote a una pared o silla si lo necesitas',
      'Mantén el torso erguido y la pelvis estable',
      'Baja en vertical con control hasta flexionar ambas rodillas',
      'Empuja con la pierna delantera para volver',
      'Haz todas las repeticiones antes de cambiar de lado',
    ],
    variants: [
      { name: 'Supported Split Squat' },
      { name: 'Tempo Supported Split Squat', descriptionSuffix: 'Se enfatiza la fase de descenso para mejorar control articular.' },
      { name: 'Paused Supported Split Squat', descriptionSuffix: 'Incluye una breve pausa abajo para ganar estabilidad.' },
      { name: 'Supported Split Squat Iso Hold', descriptionSuffix: 'Mantiene la posición media unos segundos para aumentar resistencia local.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Zancada atrás asistida con apoyo para mejorar fuerza de piernas y control de cadera.',
    instructions: [
      'Ponte de pie junto a un apoyo estable',
      'Da un paso atrás con una pierna manteniendo el torso alto',
      'Baja hasta una posición cómoda y estable',
      'Empuja con la pierna delantera para volver arriba',
      'Alterna lados de forma suave y controlada',
    ],
    variants: [
      { name: 'Reverse Lunge to Chair Support' },
      { name: 'Tempo Reverse Lunge to Chair Support', descriptionSuffix: 'La bajada lenta ayuda a mejorar estabilidad y confianza.' },
      { name: 'Paused Reverse Lunge to Chair Support', descriptionSuffix: 'La pausa en el fondo aumenta control y percepción de apoyo.' },
      { name: 'Alternating Reverse Lunge to Chair Support', descriptionSuffix: 'Alterna repeticiones para mejorar coordinación entre ambos lados.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Zancada lateral asistida para aductores, glúteos y movilidad en plano frontal.',
    instructions: [
      'Colócate de pie con ayuda de una silla o pared si la necesitas',
      'Da un paso lateral amplio',
      'Carga la cadera hacia atrás sobre la pierna que se flexiona',
      'Mantén la otra pierna más extendida y el pecho elevado',
      'Empuja para regresar al centro y cambia de lado',
    ],
    variants: [
      { name: 'Supported Lateral Lunge' },
      { name: 'Tempo Supported Lateral Lunge', descriptionSuffix: 'La fase excéntrica lenta mejora movilidad y control.' },
      { name: 'Paused Supported Lateral Lunge', descriptionSuffix: 'La pausa breve abajo favorece estabilidad y conciencia corporal.' },
      { name: 'Supported Lateral Lunge Reach', descriptionSuffix: 'Añade un alcance al frente para integrar control del tronco.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Subida a cajón o escalón con mancuernas para fuerza unilateral y equilibrio.',
    instructions: [
      'Sujeta una mancuerna en cada mano y colócate frente a un escalón estable',
      'Apoya completamente un pie sobre la superficie',
      'Empuja con esa pierna para subir',
      'Controla la bajada sin dejarte caer',
      'Completa el lado y luego cambia',
    ],
    variants: [
      { name: 'Dumbbell Step-Up' },
      { name: 'Tempo Dumbbell Step-Up', descriptionSuffix: 'La bajada lenta mejora estabilidad y tolerancia articular.' },
      { name: 'Paused Dumbbell Step-Up', descriptionSuffix: 'La pausa arriba refuerza equilibrio unilateral.' },
      { name: 'Alternating Dumbbell Step-Up', descriptionSuffix: 'Alterna lados para trabajar coordinación y ritmo.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Glúteos',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Bisagra unilateral con apoyo para glúteos, isquios y equilibrio.',
    instructions: [
      'Sujeta una mancuerna y apóyate con la otra mano si lo necesitas',
      'Carga el peso sobre una sola pierna',
      'Lleva la cadera hacia atrás manteniendo la espalda neutra',
      'Siente la tensión en glúteo e isquios',
      'Vuelve a la posición inicial empujando la cadera al frente',
    ],
    variants: [
      { name: 'Supported Single-Leg Dumbbell Romanian Deadlift' },
      { name: 'Tempo Supported Single-Leg Dumbbell Romanian Deadlift', descriptionSuffix: 'La bajada lenta mejora control y estabilidad.' },
      { name: 'Paused Supported Single-Leg Dumbbell Romanian Deadlift', descriptionSuffix: 'La pausa abajo aumenta control postural.' },
      { name: 'Contralateral Supported Single-Leg Dumbbell Romanian Deadlift', descriptionSuffix: 'La carga contralateral aumenta el reto de estabilidad.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Glúteos',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Bisagra de cadera con banda para reforzar cadena posterior con baja carga articular.',
    instructions: [
      'Pisa la banda y coloca el otro extremo sobre hombros o trapecios',
      'Desbloquea ligeramente las rodillas',
      'Lleva la cadera hacia atrás sin curvar la espalda',
      'Siente tensión en glúteos e isquios',
      'Vuelve a subir empujando las caderas al frente',
    ],
    variants: [
      { name: 'Banded Good Morning' },
      { name: 'Tempo Banded Good Morning', descriptionSuffix: 'La fase de bajada se alarga para mejorar el patrón de bisagra.' },
      { name: 'Paused Banded Good Morning', descriptionSuffix: 'Incluye una pausa breve en la posición estirada.' },
      { name: 'Staggered Banded Good Morning', descriptionSuffix: 'La base escalonada aumenta control de pelvis y pies.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Glúteos',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Puente con marcha alterna para glúteos, pelvis y estabilidad del core.',
    instructions: [
      'Acuéstate boca arriba con rodillas flexionadas',
      'Eleva las caderas hasta formar una línea estable',
      'Levanta un pie unos centímetros sin mover la pelvis',
      'Apóyalo y alterna con la otra pierna',
      'Mantén abdomen y glúteos activos todo el tiempo',
    ],
    variants: [
      { name: 'Glute Bridge March' },
      { name: 'Tempo Glute Bridge March', descriptionSuffix: 'La marcha lenta aumenta el control lumbo-pélvico.' },
      { name: 'Paused Glute Bridge March', descriptionSuffix: 'La pausa con una pierna elevada desafía más la estabilidad.' },
      { name: 'Glute Bridge March with Reach', descriptionSuffix: 'Añade un alcance de brazos para mayor coordinación total.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Glúteos',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Trabajo lateral en colchoneta para glúteo medio y estabilidad de cadera.',
    instructions: [
      'Coloca una mini banda por encima de las rodillas',
      'Túmbate de lado con rodillas flexionadas',
      'Mantén pies juntos y abre la rodilla superior',
      'Evita girar la pelvis hacia atrás',
      'Baja con control y cambia de lado al terminar',
    ],
    variants: [
      { name: 'Banded Clamshell' },
      { name: 'Tempo Banded Clamshell', descriptionSuffix: 'La apertura lenta mejora activación y control.' },
      { name: 'Paused Banded Clamshell', descriptionSuffix: 'Mantén la rodilla abierta un instante para reforzar glúteo medio.' },
      { name: 'Banded Clamshell Iso Hold', descriptionSuffix: 'La variante isométrica enfatiza resistencia local de cadera.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Glúteos',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Abducción de cadera con banda para glúteo medio y control de pelvis.',
    instructions: [
      'Coloca la banda por encima de tobillos o rodillas',
      'Ponte erguido con ligera flexión de rodillas',
      'Abre una pierna lateralmente sin inclinar el tronco',
      'Vuelve lentamente manteniendo tensión en la banda',
      'Completa el lado antes de cambiar',
    ],
    variants: [
      { name: 'Banded Hip Abduction' },
      { name: 'Tempo Banded Hip Abduction', descriptionSuffix: 'La subida lenta favorece control y estabilidad.' },
      { name: 'Paused Banded Hip Abduction', descriptionSuffix: 'La pausa arriba aumenta activación del glúteo medio.' },
      { name: 'Alternating Banded Hip Abduction', descriptionSuffix: 'Alterna lados para un trabajo más dinámico y coordinado.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Banda elástica',
    difficulty: 'Intermedio',
    description: 'Curl femoral con banda para reforzar isquios sin necesidad de máquina.',
    instructions: [
      'Ancla la banda y colócala en los tobillos',
      'Acuéstate sobre la colchoneta en una posición cómoda según el anclaje',
      'Flexiona las rodillas acercando los talones',
      'Aprieta isquiotibiales al final',
      'Extiende lentamente las piernas',
    ],
    variants: [
      { name: 'Supine Banded Hamstring Curl' },
      { name: 'Tempo Supine Banded Hamstring Curl', descriptionSuffix: 'La fase de extensión se hace lenta para aumentar control.' },
      { name: 'Paused Supine Banded Hamstring Curl', descriptionSuffix: 'La pausa en flexión refuerza la activación femoral.' },
      { name: 'Alternating Supine Banded Hamstring Curl', descriptionSuffix: 'El trabajo alterno ayuda a equilibrar ambos lados.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Elevación de talones para fortalecer gemelos y mejorar función del tobillo.',
    instructions: [
      'Ponte de pie con apoyo cercano si lo necesitas',
      'Eleva los talones lo máximo posible',
      'Haz una pausa breve arriba',
      'Baja despacio sin perder alineación',
      'Mantén el peso repartido sobre el antepié',
    ],
    variants: [
      { name: 'Standing Calf Raise' },
      { name: 'Tempo Standing Calf Raise', descriptionSuffix: 'El descenso lento mejora control de tobillo y gemelo.' },
      { name: 'Paused Standing Calf Raise', descriptionSuffix: 'La pausa arriba aumenta activación y equilibrio.' },
      { name: 'Single-Leg Standing Calf Raise', descriptionSuffix: 'La versión unilateral aumenta fuerza y estabilidad.' },
    ],
  },
  {
    category: 'Isométrico',
    muscleGroup: 'Piernas',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Sentadilla isométrica en pared para cuádriceps y resistencia local con baja demanda técnica.',
    instructions: [
      'Apoya la espalda en la pared',
      'Deslízate hasta una flexión cómoda de rodillas',
      'Mantén abdomen firme y pies bien apoyados',
      'Respira de forma tranquila sin perder postura',
      'Sube con control al terminar el tiempo',
    ],
    variants: [
      { name: 'Wall Sit' },
      { name: 'Wall Sit Heel Raise', descriptionSuffix: 'Añade elevaciones de talón para integrar tobillo y gemelo.' },
      { name: 'Wall Sit Iso Hold with Reach', descriptionSuffix: 'El alcance de brazos aumenta el reto del tronco.' },
      { name: 'Alternating Wall Sit March', descriptionSuffix: 'La marcha alterna añade estabilidad y control del core.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Espalda',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Remo sentado con banda para espalda alta, dorsales y mejora postural.',
    instructions: [
      'Siéntate con piernas extendidas y la banda alrededor de los pies',
      'Mantén el pecho abierto y los hombros bajos',
      'Tira de los codos hacia atrás',
      'Aprieta escápulas al final del movimiento',
      'Vuelve lentamente sin perder postura',
    ],
    variants: [
      { name: 'Seated Resistance Band Row' },
      { name: 'Tempo Seated Resistance Band Row', descriptionSuffix: 'La vuelta lenta mejora control escapular.' },
      { name: 'Paused Seated Resistance Band Row', descriptionSuffix: 'La pausa atrás enfatiza retracción y postura.' },
      { name: 'Wide Grip Seated Resistance Band Row', descriptionSuffix: 'El agarre más ancho enfatiza espalda alta y deltoides posteriores.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Espalda',
    equipment: 'Banda elástica',
    difficulty: 'Intermedio',
    description: 'Remo unilateral con banda desde posición sentada para equilibrar ambos lados.',
    instructions: [
      'Siéntate y fija la banda con un pie o punto estable',
      'Tira de un solo codo hacia la cadera',
      'Evita girar el tronco al remar',
      'Mantén el cuello largo y el pecho abierto',
      'Regresa con control antes de cambiar de lado',
    ],
    variants: [
      { name: 'Single-Arm Seated Resistance Band Row' },
      { name: 'Tempo Single-Arm Seated Resistance Band Row', descriptionSuffix: 'La fase excéntrica lenta mejora control unilateral.' },
      { name: 'Paused Single-Arm Seated Resistance Band Row', descriptionSuffix: 'La pausa atrás ayuda a sentir mejor la espalda.' },
      { name: 'Alternating Single-Arm Seated Resistance Band Row', descriptionSuffix: 'Alterna lados de forma rítmica y controlada.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Espalda',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Remo en cuadrupedia para integrar fuerza de espalda y estabilidad del tronco.',
    instructions: [
      'Colócate a cuatro apoyos con una mancuerna al lado',
      'Apoya firmemente rodillas y mano contraria',
      'Rema llevando el codo hacia la cadera',
      'Evita rotar el torso durante el gesto',
      'Baja la mancuerna con control antes de cambiar',
    ],
    variants: [
      { name: 'Bird Dog Row' },
      { name: 'Tempo Bird Dog Row', descriptionSuffix: 'La subida y bajada lentas mejoran control y coordinación.' },
      { name: 'Paused Bird Dog Row', descriptionSuffix: 'La pausa arriba refuerza espalda y estabilidad.' },
      { name: 'Alternating Bird Dog Row', descriptionSuffix: 'Alternar lados exige más coordinación cruzada.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Espalda',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Pullover tumbado en colchoneta para dorsales, serrato y control costal.',
    instructions: [
      'Túmbate con una mancuerna sostenida con ambas manos sobre el pecho',
      'Mantén una ligera flexión en codos',
      'Lleva la carga por detrás de la cabeza hasta donde controles',
      'Vuelve al inicio activando dorsales y pecho',
      'Evita arquear en exceso la zona lumbar',
    ],
    variants: [
      { name: 'Dumbbell Pullover on Floor' },
      { name: 'Tempo Dumbbell Pullover on Floor', descriptionSuffix: 'La bajada lenta mejora control escapular y torácico.' },
      { name: 'Paused Dumbbell Pullover on Floor', descriptionSuffix: 'La pausa en el estiramiento ayuda a ganar conciencia del recorrido.' },
      { name: 'Alternating Dumbbell Pullover Reach', descriptionSuffix: 'El alcance alterno al volver añade control del tronco.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Hombros',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Rotación externa con banda para reforzar manguito rotador y estabilidad del hombro.',
    instructions: [
      'Sujeta la banda con codos pegados al cuerpo a 90 grados',
      'Mantén el pecho abierto y hombros bajos',
      'Separa las manos girando externamente los hombros',
      'Haz una pausa breve al final',
      'Regresa lentamente sin perder alineación',
    ],
    variants: [
      { name: 'Resistance Band External Rotation' },
      { name: 'Tempo Resistance Band External Rotation', descriptionSuffix: 'La vuelta lenta mejora el control fino del hombro.' },
      { name: 'Paused Resistance Band External Rotation', descriptionSuffix: 'La pausa final refuerza el trabajo del manguito.' },
      { name: 'Alternating Resistance Band External Rotation', descriptionSuffix: 'El trabajo alterno mejora simetría entre lados.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Hombros',
    equipment: 'Banda elástica',
    difficulty: 'Intermedio',
    description: 'Combina tracción facial y rotación externa para espalda alta y hombro sano.',
    instructions: [
      'Ancla la banda a la altura de la cara',
      'Tira hacia la nariz separando las manos',
      'Mantén los hombros lejos de las orejas',
      'Aprieta escápulas al final',
      'Extiende de nuevo los brazos con control',
    ],
    variants: [
      { name: 'Face Pull to External Rotation' },
      { name: 'Tempo Face Pull to External Rotation', descriptionSuffix: 'El ritmo lento mejora postura y control escapular.' },
      { name: 'Paused Face Pull to External Rotation', descriptionSuffix: 'La pausa final refuerza la posición de hombro estable.' },
      { name: 'Tall-Kneeling Face Pull to External Rotation', descriptionSuffix: 'La media rodilla alta añade trabajo de core y pelvis.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Pecho',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Flexión en pared de muy bajo impacto para recuperar fuerza de empuje.',
    instructions: [
      'Colócate frente a una pared con manos a la altura del pecho',
      'Inclina el cuerpo manteniendo una línea recta',
      'Dobla codos acercando el pecho a la pared',
      'Empuja hasta volver a la posición inicial',
      'Mantén abdomen y glúteos activos',
    ],
    variants: [
      { name: 'Wall Push-ups' },
      { name: 'Tempo Wall Push-ups', descriptionSuffix: 'La bajada lenta mejora técnica y control.' },
      { name: 'Paused Wall Push-ups', descriptionSuffix: 'La pausa cerca de la pared aumenta conciencia del recorrido.' },
      { name: 'Narrow Wall Push-ups', descriptionSuffix: 'La base más estrecha carga más tríceps y control de hombro.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Pecho',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Flexión inclinada sobre apoyo elevado para pecho y brazos con menor carga que en el suelo.',
    instructions: [
      'Apoya las manos en un banco o sofá firme',
      'Camina con los pies atrás hasta formar una línea recta',
      'Desciende el pecho controlando hombros y tronco',
      'Empuja hasta extender los brazos',
      'Evita hundir la zona lumbar',
    ],
    variants: [
      { name: 'Incline Push-ups on Bench' },
      { name: 'Tempo Incline Push-ups on Bench', descriptionSuffix: 'La fase de bajada lenta mejora control del gesto.' },
      { name: 'Paused Incline Push-ups on Bench', descriptionSuffix: 'La pausa abajo refuerza estabilidad escapular.' },
      { name: 'Alternating Incline Push-ups on Bench', descriptionSuffix: 'La versión alterna introduce un componente adicional de estabilidad.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Pecho',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Press en el suelo amable con los hombros para desarrollar fuerza de pecho y tríceps en casa.',
    instructions: [
      'Túmbate con una mancuerna en cada mano',
      'Coloca los codos apoyados en el suelo',
      'Empuja las mancuernas arriba hasta extender los brazos',
      'Baja hasta tocar suavemente el suelo con los tríceps',
      'Mantén las muñecas neutras y controladas',
    ],
    variants: [
      { name: 'Dumbbell Floor Press' },
      { name: 'Tempo Dumbbell Floor Press', descriptionSuffix: 'La bajada lenta aumenta control y tiempo bajo tensión.' },
      { name: 'Paused Dumbbell Floor Press', descriptionSuffix: 'La pausa en el suelo mejora estabilidad del hombro.' },
      { name: 'Alternating Dumbbell Floor Press', descriptionSuffix: 'La versión alterna exige más control del tronco.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Pecho',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Press sentado con banda para pecho y brazos con mucha estabilidad y baja complejidad técnica.',
    instructions: [
      'Siéntate erguido y pasa la banda alrededor de la espalda alta',
      'Sujeta un extremo en cada mano',
      'Empuja las manos al frente hasta extender los brazos',
      'Mantén el pecho abierto y hombros bajos',
      'Vuelve lentamente al punto de partida',
    ],
    variants: [
      { name: 'Seated Band Chest Press' },
      { name: 'Tempo Seated Band Chest Press', descriptionSuffix: 'La extensión y la vuelta lentas refuerzan control y postura.' },
      { name: 'Paused Seated Band Chest Press', descriptionSuffix: 'La pausa adelante mejora estabilidad del tronco.' },
      { name: 'Alternating Seated Band Chest Press', descriptionSuffix: 'La versión alterna añade demanda antirotacional.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Hombros',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Press unilateral en media rodilla para hombro, core y estabilidad de cadera.',
    instructions: [
      'Colócate en media rodilla sobre la colchoneta',
      'Sujeta una mancuerna a la altura del hombro',
      'Aprieta glúteo de la pierna retrasada',
      'Empuja la mancuerna por encima de la cabeza',
      'Baja con control y cambia de lado',
    ],
    variants: [
      { name: 'Half-Kneeling Single-Arm Dumbbell Press' },
      { name: 'Tempo Half-Kneeling Single-Arm Dumbbell Press', descriptionSuffix: 'La bajada lenta mejora control del hombro y del core.' },
      { name: 'Paused Half-Kneeling Single-Arm Dumbbell Press', descriptionSuffix: 'La pausa arriba refuerza alineación y estabilidad.' },
      { name: 'Alternating Half-Kneeling Single-Arm Dumbbell Press', descriptionSuffix: 'Alternar lados incrementa coordinación y control postural.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Hombros',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Press Arnold sentado para hombros con mayor control del torso y del recorrido.',
    instructions: [
      'Siéntate erguido con mancuernas delante del pecho',
      'Comienza con palmas mirando hacia ti',
      'Empuja mientras giras las manos al frente',
      'Termina con brazos arriba sin encoger hombros',
      'Baja invirtiendo el movimiento',
    ],
    variants: [
      { name: 'Seated Arnold Press' },
      { name: 'Tempo Seated Arnold Press', descriptionSuffix: 'La bajada lenta mejora control y postura.' },
      { name: 'Paused Seated Arnold Press', descriptionSuffix: 'La pausa arriba ayuda a estabilizar el hombro.' },
      { name: 'Alternating Seated Arnold Press', descriptionSuffix: 'Alternar lados exige más control del core.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Hombros',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Elevación lateral sentada para fortalecer hombro medio reduciendo balanceos.',
    instructions: [
      'Siéntate con una mancuerna en cada mano',
      'Mantén codos ligeramente flexionados',
      'Eleva brazos hacia los lados hasta la altura del hombro',
      'Haz una breve pausa controlada',
      'Baja despacio sin balancearte',
    ],
    variants: [
      { name: 'Seated Lateral Raise' },
      { name: 'Tempo Seated Lateral Raise', descriptionSuffix: 'La bajada lenta mejora control escapular.' },
      { name: 'Paused Seated Lateral Raise', descriptionSuffix: 'La pausa arriba aumenta activación del deltoides medio.' },
      { name: 'Alternating Seated Lateral Raise', descriptionSuffix: 'Alternar brazos reduce compensaciones y mejora el control.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Hombros',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Separación con banda para hombros posteriores y mejor postura torácica.',
    instructions: [
      'Sujeta la banda con ambos brazos al frente',
      'Mantén costillas abajo y cuello largo',
      'Abre los brazos separando la banda',
      'Aprieta las escápulas al final',
      'Vuelve con control al centro',
    ],
    variants: [
      { name: 'Banded Pull Apart' },
      { name: 'Tempo Banded Pull Apart', descriptionSuffix: 'El retorno lento mejora control escapular.' },
      { name: 'Paused Banded Pull Apart', descriptionSuffix: 'La pausa abierta refuerza espalda alta y hombros posteriores.' },
      { name: 'Overhead Banded Pull Apart', descriptionSuffix: 'La variante por encima de la cabeza integra movilidad torácica y escapular.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Brazos',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Curl martillo sentado para bíceps y antebrazo con máxima estabilidad del tronco.',
    instructions: [
      'Siéntate erguido con palmas enfrentadas',
      'Mantén los codos pegados al cuerpo',
      'Flexiona sin balancear el torso',
      'Aprieta arriba un instante',
      'Baja lentamente hasta extender los brazos',
    ],
    variants: [
      { name: 'Seated Hammer Curl' },
      { name: 'Tempo Seated Hammer Curl', descriptionSuffix: 'La fase excéntrica lenta mejora control y estímulo.' },
      { name: 'Paused Seated Hammer Curl', descriptionSuffix: 'La pausa arriba refuerza la contracción del bíceps.' },
      { name: 'Alternating Seated Hammer Curl', descriptionSuffix: 'Alternar lados mejora control y reduce balanceos.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Brazos',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Curl sentado con supinación para bíceps y control de antebrazo.',
    instructions: [
      'Siéntate con una mancuerna en cada mano',
      'Empieza con agarre neutro o semisupino',
      'Gira la palma hacia arriba mientras flexionas el codo',
      'Aprieta al llegar arriba',
      'Desciende lentamente hasta la posición inicial',
    ],
    variants: [
      { name: 'Seated Supinating Curl' },
      { name: 'Tempo Seated Supinating Curl', descriptionSuffix: 'El descenso lento mejora control del recorrido.' },
      { name: 'Paused Seated Supinating Curl', descriptionSuffix: 'La pausa final aumenta la sensación de contracción.' },
      { name: 'Alternating Seated Supinating Curl', descriptionSuffix: 'Alternar lados ayuda a trabajar con más precisión técnica.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Brazos',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Extensión de tríceps con mancuernas y bajo impacto para fortalecer brazos y estabilidad escapular.',
    instructions: [
      'Inclina ligeramente el torso con una mancuerna en cada mano',
      'Mantén codos pegados al costado',
      'Extiende los codos hacia atrás sin mover hombros',
      'Aprieta los tríceps al final',
      'Regresa lentamente a 90 grados',
    ],
    variants: [
      { name: 'Dumbbell Triceps Kickback' },
      { name: 'Tempo Dumbbell Triceps Kickback', descriptionSuffix: 'La extensión y la vuelta lentas mejoran control y estímulo.' },
      { name: 'Paused Dumbbell Triceps Kickback', descriptionSuffix: 'La pausa final acentúa el trabajo del tríceps.' },
      { name: 'Alternating Dumbbell Triceps Kickback', descriptionSuffix: 'La versión alterna añade estabilidad del tronco.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Brazos',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Extensión por encima de la cabeza con banda para tríceps y control del hombro.',
    instructions: [
      'Ancla o pisa la banda y lleva las manos detrás de la cabeza',
      'Mantén los codos apuntando al frente',
      'Extiende los brazos por encima de la cabeza',
      'Aprieta tríceps al final del recorrido',
      'Baja con control sin abrir demasiado los codos',
    ],
    variants: [
      { name: 'Overhead Band Triceps Extension' },
      { name: 'Tempo Overhead Band Triceps Extension', descriptionSuffix: 'La fase de bajada se ralentiza para ganar control.' },
      { name: 'Paused Overhead Band Triceps Extension', descriptionSuffix: 'La pausa arriba mejora estabilidad del codo.' },
      { name: 'Half-Kneeling Overhead Band Triceps Extension', descriptionSuffix: 'La posición en media rodilla añade trabajo de core y pelvis.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Ejercicio de estabilidad cruzada para columna, hombros y cadera.',
    instructions: [
      'Colócate en cuadrupedia sobre una colchoneta',
      'Activa el abdomen sin redondear la espalda',
      'Extiende un brazo y la pierna contraria',
      'Haz una pausa breve con la pelvis estable',
      'Vuelve al centro y alterna el lado',
    ],
    variants: [
      { name: 'Bird Dog' },
      { name: 'Tempo Bird Dog', descriptionSuffix: 'Los movimientos lentos aumentan control y coordinación.' },
      { name: 'Paused Bird Dog', descriptionSuffix: 'La pausa extendida mejora estabilidad central.' },
      { name: 'Bird Dog with Elbow-to-Knee', descriptionSuffix: 'Añade un cierre controlado para integrar más el core.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Variante accesible del dead bug para reforzar control lumbo-pélvico.',
    instructions: [
      'Acuéstate boca arriba con piernas elevadas a 90 grados',
      'Presiona suavemente la zona lumbar contra el suelo',
      'Baja un talón hacia el suelo sin perder estabilidad',
      'Vuelve al centro y alterna el otro lado',
      'Respira con calma manteniendo el abdomen activo',
    ],
    variants: [
      { name: 'Dead Bug Heel Taps' },
      { name: 'Tempo Dead Bug Heel Taps', descriptionSuffix: 'La bajada lenta mejora control de pelvis y respiración.' },
      { name: 'Paused Dead Bug Heel Taps', descriptionSuffix: 'La pausa cerca del suelo aumenta el reto anti-extensión.' },
      { name: 'Alternating Dead Bug Heel Taps', descriptionSuffix: 'El ritmo alterno continuo mejora coordinación y resistencia del core.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Press anti-extensión en posición arrodillada para core, glúteos y control postural.',
    instructions: [
      'Arrodíllate sobre la colchoneta sosteniendo una banda anclada detrás',
      'Lleva las manos al esternón',
      'Activa abdomen y glúteos',
      'Extiende los brazos al frente sin arquear la espalda',
      'Vuelve lentamente al pecho',
    ],
    variants: [
      { name: 'Tall-Kneeling Band Press-Out' },
      { name: 'Tempo Tall-Kneeling Band Press-Out', descriptionSuffix: 'La vuelta lenta mejora control anti-extensión.' },
      { name: 'Paused Tall-Kneeling Band Press-Out', descriptionSuffix: 'La pausa adelante aumenta el trabajo del core.' },
      { name: 'Alternating Tall-Kneeling Band Press-Out', descriptionSuffix: 'La alternancia añade un componente antirotacional extra.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Marcha unilateral con mancuerna para estabilidad del tronco, equilibrio y control lateral.',
    instructions: [
      'Sujeta una mancuerna en una sola mano al lado del cuerpo',
      'Ponte erguido sin inclinarte hacia la carga',
      'Eleva una rodilla a la vez como si marcharas',
      'Controla el cuerpo para evitar balanceos',
      'Mantén un ritmo lento y constante',
    ],
    variants: [
      { name: 'Suitcase March' },
      { name: 'Tempo Suitcase March', descriptionSuffix: 'La marcha lenta aumenta el reto de equilibrio y control lateral.' },
      { name: 'Paused Suitcase March', descriptionSuffix: 'La pausa con rodilla arriba refuerza estabilidad y postura.' },
      { name: 'Alternating Suitcase March', descriptionSuffix: 'Cambiar la carga de mano entre series equilibra ambos lados.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Full Body',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Marcha con mancuernas en rack frontal para postura, core y resistencia local.',
    instructions: [
      'Sostén una o dos mancuernas a la altura de los hombros',
      'Mantén el tronco alto y el abdomen activo',
      'Marcha elevando una rodilla cada vez',
      'Evita balancearte o perder la postura',
      'Continúa a ritmo estable durante toda la serie',
    ],
    variants: [
      { name: 'Front Rack Dumbbell March' },
      { name: 'Tempo Front Rack Dumbbell March', descriptionSuffix: 'La marcha lenta aumenta control del core y respiración.' },
      { name: 'Paused Front Rack Dumbbell March', descriptionSuffix: 'La pausa con rodilla arriba mejora equilibrio y estabilidad.' },
      { name: 'Single-Arm Front Rack Dumbbell March', descriptionSuffix: 'La carga unilateral añade un reto antirotacional claro.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Peso corporal',
    difficulty: 'Intermedio',
    description: 'Plancha alta con desplazamiento de pies para core, hombros y estabilidad sin impacto.',
    instructions: [
      'Adopta una plancha alta con manos bajo los hombros',
      'Mantén el cuerpo alineado y abdomen firme',
      'Lleva un pie hacia un lado y vuelve al centro',
      'Alterna lados sin mover demasiado la pelvis',
      'Respira de forma constante durante el ejercicio',
    ],
    variants: [
      { name: 'Toe Tap Plank' },
      { name: 'Tempo Toe Tap Plank', descriptionSuffix: 'El movimiento lento aumenta el control antirotacional.' },
      { name: 'Paused Toe Tap Plank', descriptionSuffix: 'La pausa lateral mejora estabilidad y conciencia del tronco.' },
      { name: 'Alternating Toe Tap Plank', descriptionSuffix: 'El ritmo alterno continuo desarrolla resistencia del core.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Glúteos',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Elevación lateral de pierna en colchoneta para glúteo medio y control de cadera.',
    instructions: [
      'Túmbate de lado con piernas alineadas',
      'Activa el abdomen para no girar la pelvis',
      'Eleva la pierna superior con control',
      'Haz una breve pausa arriba',
      'Desciende lentamente y cambia de lado al terminar',
    ],
    variants: [
      { name: 'Side-Lying Leg Raise' },
      { name: 'Tempo Side-Lying Leg Raise', descriptionSuffix: 'La subida y bajada lentas mejoran activación del glúteo medio.' },
      { name: 'Paused Side-Lying Leg Raise', descriptionSuffix: 'La pausa final aumenta el trabajo isométrico lateral.' },
      { name: 'Side-Lying Leg Raise Pulse', descriptionSuffix: 'Los pulsos cortos añaden resistencia local sin impacto.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Dead bug con presión isométrica sobre banda para integrar anti-extensión y coordinación.',
    instructions: [
      'Túmbate boca arriba con la banda anclada detrás o sujeta por las manos',
      'Mantén presión activa de la banda sobre el pecho',
      'Alterna el descenso de una pierna sin perder la estabilidad lumbar',
      'Vuelve al centro y cambia de lado',
      'Mantén la respiración controlada durante toda la serie',
    ],
    variants: [
      { name: 'Banded Dead Bug Press' },
      { name: 'Tempo Banded Dead Bug Press', descriptionSuffix: 'La bajada lenta refuerza el control anti-extensión.' },
      { name: 'Paused Banded Dead Bug Press', descriptionSuffix: 'La pausa con pierna extendida aumenta el trabajo del abdomen.' },
      { name: 'Alternating Banded Dead Bug Press', descriptionSuffix: 'El patrón alterno continuo mejora coordinación cruzada.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Sentadilla con mancuerna a un objetivo para mejorar profundidad, control y confianza.',
    instructions: [
      'Sostén una mancuerna al pecho y colócate delante de una referencia segura',
      'Desciende manteniendo el pecho alto y las rodillas alineadas',
      'Toca suavemente la referencia',
      'Empuja el suelo para volver a subir',
      'Mantén la respiración fluida durante todo el movimiento',
    ],
    variants: [
      { name: 'Dumbbell Target Squat' },
      { name: 'Tempo Dumbbell Target Squat', descriptionSuffix: 'La bajada lenta mejora control y tolerancia al rango.' },
      { name: 'Paused Dumbbell Target Squat', descriptionSuffix: 'La pausa abajo aumenta estabilidad en cadera y rodilla.' },
      { name: 'Alternating Dumbbell Target Squat Reach', descriptionSuffix: 'Añade un alcance alterno al subir para integrar coordinación.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Patrón de bisagra de cadera sin carga para aprender a proteger la espalda y activar glúteos.',
    instructions: [
      'Ponte de pie con pies al ancho de caderas',
      'Coloca manos sobre las crestas ilíacas o en el pecho',
      'Lleva la cadera hacia atrás manteniendo la espalda neutra',
      'Siente tensión en la parte posterior de las piernas',
      'Vuelve a la posición inicial apretando glúteos',
    ],
    variants: [
      { name: 'Bodyweight Hip Hinge' },
      { name: 'Tempo Bodyweight Hip Hinge', descriptionSuffix: 'El descenso lento mejora aprendizaje del patrón.' },
      { name: 'Paused Bodyweight Hip Hinge', descriptionSuffix: 'La pausa en la posición de bisagra refuerza control postural.' },
      { name: 'Alternating Bodyweight Hip Hinge Reach', descriptionSuffix: 'El alcance alterno añade estabilidad y coordinación.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Espalda',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Jalón vertical de rodillas con banda para dorsales y postura desde casa.',
    instructions: [
      'Ancla la banda por encima de la cabeza',
      'Colócate de rodillas sobre la colchoneta',
      'Tira de los codos hacia abajo y atrás',
      'Lleva las manos hacia la parte alta del pecho',
      'Regresa lentamente hasta extender los brazos',
    ],
    variants: [
      { name: 'Kneeling Resistance Band Lat Pulldown' },
      { name: 'Tempo Kneeling Resistance Band Lat Pulldown', descriptionSuffix: 'La vuelta lenta mejora control de escápulas.' },
      { name: 'Paused Kneeling Resistance Band Lat Pulldown', descriptionSuffix: 'La pausa final enfatiza dorsales y espalda alta.' },
      { name: 'Alternating Kneeling Resistance Band Lat Pulldown', descriptionSuffix: 'La versión alterna añade coordinación y control unilateral.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Hombros',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Elevación frontal sentada para hombros y control del tronco.',
    instructions: [
      'Siéntate erguido con una mancuerna en cada mano',
      'Mantén abdomen activo y cuello largo',
      'Eleva los brazos al frente hasta la altura de los hombros',
      'Pausa brevemente sin encoger hombros',
      'Baja con control al inicio',
    ],
    variants: [
      { name: 'Seated Front Raise' },
      { name: 'Tempo Seated Front Raise', descriptionSuffix: 'La bajada lenta mejora control del hombro.' },
      { name: 'Paused Seated Front Raise', descriptionSuffix: 'La pausa arriba aumenta tiempo bajo tensión.' },
      { name: 'Alternating Seated Front Raise', descriptionSuffix: 'Alternar brazos reduce compensaciones y mejora la técnica.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Hombros',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Apertura posterior inclinada sentada para deltoides posterior y postura.',
    instructions: [
      'Siéntate al borde del banco o silla e inclina el torso',
      'Deja colgar las mancuernas bajo los hombros',
      'Abre los brazos hacia los lados con ligera flexión de codos',
      'Aprieta la parte alta de la espalda al final',
      'Desciende lentamente sin balancear el cuerpo',
    ],
    variants: [
      { name: 'Seated Rear Delt Fly' },
      { name: 'Tempo Seated Rear Delt Fly', descriptionSuffix: 'El retorno lento mejora control escapular.' },
      { name: 'Paused Seated Rear Delt Fly', descriptionSuffix: 'La pausa abierta aumenta activación posterior.' },
      { name: 'Alternating Seated Rear Delt Fly', descriptionSuffix: 'Alternar lados mejora coordinación y control del tronco.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Plancha lateral modificada para oblicuos, estabilidad de hombro y cadera.',
    instructions: [
      'Colócate de lado apoyando antebrazo y rodillas o pies según nivel',
      'Eleva la pelvis hasta alinear hombros y caderas',
      'Mantén abdomen activo y cuello neutro',
      'Respira sin perder la posición',
      'Cambia de lado al finalizar el tiempo',
    ],
    variants: [
      { name: 'Modified Side Plank' },
      { name: 'Tempo Modified Side Plank', descriptionSuffix: 'La entrada y salida lentas mejoran control lateral.' },
      { name: 'Paused Modified Side Plank Lift', descriptionSuffix: 'Eleva y mantén la cadera un instante para más trabajo oblicuo.' },
      { name: 'Alternating Modified Side Plank Reach', descriptionSuffix: 'El alcance controlado añade coordinación y estabilidad escapular.' },
    ],
  },
  {
    category: 'Balance',
    muscleGroup: 'Piernas',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Equilibrio a una pierna para tobillo, cadera y control postural.',
    instructions: [
      'Ponte de pie cerca de un apoyo si lo necesitas',
      'Eleva una pierna unos centímetros del suelo',
      'Mantén pelvis y tronco estables',
      'Sostén la postura respirando con calma',
      'Cambia de lado al terminar',
    ],
    variants: [
      { name: 'Single-Leg Balance Hold' },
      { name: 'Single-Leg Balance Hold with Reach', descriptionSuffix: 'El alcance de brazos añade un reto coordinativo suave.' },
      { name: 'Single-Leg Balance Hold with Toe Tap', descriptionSuffix: 'Los toques de pie aumentan el trabajo del tobillo y la cadera.' },
      { name: 'Single-Leg Balance Hold with Knee Drive', descriptionSuffix: 'La elevación de rodilla refuerza estabilidad y postura.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Full body',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Peso muerto a maleta con dos mancuernas para fuerza total y patrón de bisagra funcional.',
    instructions: [
      'Sostén dos mancuernas a los lados del cuerpo',
      'Lleva la cadera hacia atrás manteniendo la espalda neutra',
      'Desciende hasta una altura cómoda sin perder postura',
      'Empuja el suelo para volver a subir',
      'Aprieta glúteos al final del movimiento',
    ],
    variants: [
      { name: 'Dumbbell Suitcase Deadlift' },
      { name: 'Tempo Dumbbell Suitcase Deadlift', descriptionSuffix: 'La bajada lenta mejora técnica y control de cadera.' },
      { name: 'Paused Dumbbell Suitcase Deadlift', descriptionSuffix: 'La pausa abajo aumenta conciencia del patrón de bisagra.' },
      { name: 'Staggered Dumbbell Suitcase Deadlift', descriptionSuffix: 'La base escalonada añade estabilidad y trabajo unilateral suave.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Full body',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Carga unilateral en posición de rack para integrar core, hombro y patrón de marcha.',
    instructions: [
      'Lleva una mancuerna a la altura del hombro',
      'Mantén costillas abajo y tronco erguido',
      'Marcha lentamente o mantén la postura',
      'Evita inclinarte hacia un lado',
      'Cambia de lado tras completar el tiempo o las repeticiones',
    ],
    variants: [
      { name: 'Single-Arm Front Rack Hold' },
      { name: 'Single-Arm Front Rack Hold with March', descriptionSuffix: 'La marcha añade trabajo de equilibrio y core.' },
      { name: 'Tempo Single-Arm Front Rack Hold', descriptionSuffix: 'El control respiratorio y postural es la prioridad.' },
      { name: 'Paused Single-Arm Front Rack March', descriptionSuffix: 'La pausa con rodilla arriba enfatiza estabilidad y coordinación.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Pallof press con paso lateral corto para antirotación y estabilidad del tronco.',
    instructions: [
      'Ancla la banda a la altura del esternón y colócate de lado',
      'Sujétala frente al pecho con ambas manos',
      'Extiende los brazos al frente evitando girarte',
      'Da un paso lateral corto manteniendo la tensión',
      'Vuelve al centro con control y repite',
    ],
    variants: [
      { name: 'Lateral Step Pallof Press' },
      { name: 'Tempo Lateral Step Pallof Press', descriptionSuffix: 'El movimiento lento mejora control antirotacional.' },
      { name: 'Paused Lateral Step Pallof Press', descriptionSuffix: 'La pausa con brazos extendidos aumenta el trabajo del core.' },
      { name: 'Alternating Lateral Step Pallof Press', descriptionSuffix: 'Alternar dirección mejora coordinación y control del tronco.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Espalda',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Remo apoyado sobre muslos o banco casero para espalda media con mínima exigencia lumbar.',
    instructions: [
      'Inclina el torso con apoyo de una mano o antebrazo si hace falta',
      'Sujeta una mancuerna con la otra mano',
      'Lleva el codo hacia la cadera sin girar el tronco',
      'Aprieta la espalda al final del recorrido',
      'Baja lentamente antes de repetir',
    ],
    variants: [
      { name: 'Supported Dumbbell Row' },
      { name: 'Tempo Supported Dumbbell Row', descriptionSuffix: 'La fase excéntrica lenta mejora control y estímulo.' },
      { name: 'Paused Supported Dumbbell Row', descriptionSuffix: 'La pausa arriba ayuda a sentir mejor la espalda.' },
      { name: 'Alternating Supported Dumbbell Row', descriptionSuffix: 'Alternar lados mejora equilibrio entre ambos brazos.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Glúteos',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Puente unilateral asistido para glúteo e isquios con control del core.',
    instructions: [
      'Acuéstate boca arriba con una rodilla flexionada y la otra pierna preparada para descargar',
      'Empuja con el talón de la pierna activa',
      'Eleva la cadera manteniendo pelvis alineada',
      'Aprieta glúteo arriba',
      'Baja con control y cambia de lado',
    ],
    variants: [
      { name: 'Supported Single-Leg Glute Bridge' },
      { name: 'Tempo Supported Single-Leg Glute Bridge', descriptionSuffix: 'La bajada lenta mejora control pélvico.' },
      { name: 'Paused Supported Single-Leg Glute Bridge', descriptionSuffix: 'La pausa arriba refuerza la contracción del glúteo.' },
      { name: 'Alternating Supported Single-Leg Glute Bridge', descriptionSuffix: 'La alternancia continua añade coordinación y resistencia.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Deslizamiento de talones desde posición supina para control abdominal y pelvis.',
    instructions: [
      'Acuéstate boca arriba con rodillas flexionadas',
      'Activa el abdomen y mantén la espalda neutra',
      'Desliza un talón hacia adelante sin perder la posición del tronco',
      'Vuelve al inicio y cambia de lado',
      'Respira con calma durante toda la serie',
    ],
    variants: [
      { name: 'Supine Heel Slide' },
      { name: 'Tempo Supine Heel Slide', descriptionSuffix: 'El deslizamiento lento aumenta control lumbo-pélvico.' },
      { name: 'Paused Supine Heel Slide', descriptionSuffix: 'La pausa con pierna extendida incrementa la demanda del core.' },
      { name: 'Alternating Supine Heel Slide', descriptionSuffix: 'La alternancia continua mejora coordinación y resistencia.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Mancuernas',
    difficulty: 'Principiante',
    description: 'Peso muerto rumano con alcance frontal para integrar bisagra, equilibrio y control del tronco.',
    instructions: [
      'Sujeta una mancuerna con ambas manos o una sola según nivel',
      'Inicia la bisagra de cadera llevando glúteos atrás',
      'Alarga los brazos al frente ligeramente mientras desciendes',
      'Mantén espalda neutra y cuello largo',
      'Vuelve a subir apretando glúteos',
    ],
    variants: [
      { name: 'Reach Dumbbell Romanian Deadlift' },
      { name: 'Tempo Reach Dumbbell Romanian Deadlift', descriptionSuffix: 'La bajada lenta mejora coordinación entre tronco y cadera.' },
      { name: 'Paused Reach Dumbbell Romanian Deadlift', descriptionSuffix: 'La pausa abajo ayuda a consolidar el patrón.' },
      { name: 'Alternating Reach Dumbbell Romanian Deadlift', descriptionSuffix: 'Alternar la mano dominante cambia la demanda del core.' },
    ],
  },
  {
    category: 'Balance',
    muscleGroup: 'Glúteos',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Bisagra a una pierna con apoyo ligero para equilibrio, pie y cadera.',
    instructions: [
      'Ponte de pie cerca de un apoyo',
      'Despega ligeramente un pie del suelo',
      'Inclina el tronco desde la cadera sin redondear la espalda',
      'Mantén una ligera flexión de rodilla en la pierna de apoyo',
      'Vuelve arriba con control',
    ],
    variants: [
      { name: 'Supported Single-Leg Hip Hinge' },
      { name: 'Tempo Supported Single-Leg Hip Hinge', descriptionSuffix: 'La bajada lenta mejora control del pie y la pelvis.' },
      { name: 'Paused Supported Single-Leg Hip Hinge', descriptionSuffix: 'La pausa en bisagra añade estabilidad y conciencia corporal.' },
      { name: 'Supported Single-Leg Hip Hinge Reach', descriptionSuffix: 'El alcance frontal añade coordinación y reto al equilibrio.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Press antirotacional desde zancada estática para core y estabilidad de cadera.',
    instructions: [
      'Colócate en zancada mirando perpendicular al anclaje de la banda',
      'Sujeta la banda frente al esternón',
      'Extiende los brazos evitando que el tronco gire',
      'Mantén cadera y costillas estables',
      'Regresa con control al pecho',
    ],
    variants: [
      { name: 'Split Stance Pallof Press' },
      { name: 'Tempo Split Stance Pallof Press', descriptionSuffix: 'La extensión lenta mejora control del tronco y la pelvis.' },
      { name: 'Paused Split Stance Pallof Press', descriptionSuffix: 'La pausa con brazos extendidos aumenta el trabajo antirotacional.' },
      { name: 'Alternating Split Stance Pallof Press', descriptionSuffix: 'Cambiar la pierna adelantada equilibra la demanda entre ambos lados.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Pecho',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Apertura de pecho con banda desde posición sentada para trabajo controlado del pectoral.',
    instructions: [
      'Siéntate y pasa la banda por la espalda alta',
      'Abre los brazos ligeramente flexionados',
      'Cierra al frente como si abrazaras un barril',
      'Mantén hombros bajos y pecho abierto',
      'Regresa despacio al punto inicial',
    ],
    variants: [
      { name: 'Seated Band Chest Fly' },
      { name: 'Tempo Seated Band Chest Fly', descriptionSuffix: 'El retorno lento mejora control del hombro.' },
      { name: 'Paused Seated Band Chest Fly', descriptionSuffix: 'La pausa al cerrar enfatiza el trabajo del pecho.' },
      { name: 'Alternating Seated Band Chest Fly', descriptionSuffix: 'Alternar brazos añade un reto de estabilidad del tronco.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Espalda',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Jalón recto con banda para dorsales, serrato y control de costillas.',
    instructions: [
      'Ancla la banda por encima de la cabeza y sujeta ambos extremos',
      'Mantén los brazos casi extendidos',
      'Lleva las manos hacia los muslos sin doblar mucho los codos',
      'Aprieta dorsales al final',
      'Regresa con control al inicio',
    ],
    variants: [
      { name: 'Straight-Arm Band Pulldown' },
      { name: 'Tempo Straight-Arm Band Pulldown', descriptionSuffix: 'La vuelta lenta mejora control torácico y escapular.' },
      { name: 'Paused Straight-Arm Band Pulldown', descriptionSuffix: 'La pausa abajo intensifica el trabajo del dorsal.' },
      { name: 'Tall-Kneeling Straight-Arm Band Pulldown', descriptionSuffix: 'La posición arrodillada añade estabilidad del core.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Hombros',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Patrón Y-T-W con banda ligera para hombros, escapulas y postura.',
    instructions: [
      'Sujeta una banda ligera con ambas manos',
      'Eleva o abre los brazos según la forma marcada',
      'Mantén cuello largo y escápulas controladas',
      'Haz una pausa corta al final',
      'Vuelve despacio al inicio',
    ],
    variants: [
      { name: 'Banded Y Raise' },
      { name: 'Banded T Raise', descriptionSuffix: 'La apertura horizontal enfatiza hombros posteriores y espalda alta.' },
      { name: 'Banded W Raise', descriptionSuffix: 'La posición en W refuerza rotadores externos y control escapular.' },
      { name: 'Banded Y-T-W Flow', descriptionSuffix: 'La secuencia completa integra movilidad y estabilidad de hombro.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Lunge lateral con mancuerna goblet para aductores, glúteos y control frontal.',
    instructions: [
      'Sostén una mancuerna al pecho',
      'Da un paso lateral amplio',
      'Carga la cadera atrás sobre la pierna flexionada',
      'Mantén el pecho elevado y el pie de la otra pierna firme',
      'Empuja para volver al centro y alterna',
    ],
    variants: [
      { name: 'Goblet Lateral Lunge' },
      { name: 'Tempo Goblet Lateral Lunge', descriptionSuffix: 'La bajada lenta mejora control frontal y movilidad.' },
      { name: 'Paused Goblet Lateral Lunge', descriptionSuffix: 'La pausa abajo ayuda a ganar estabilidad en aductores y glúteos.' },
      { name: 'Alternating Goblet Lateral Lunge', descriptionSuffix: 'Alternar lados añade fluidez y coordinación.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Peso muerto a una pierna con apoyo y mancuerna ligera para equilibrio y cadena posterior.',
    instructions: [
      'Sujeta una mancuerna en la mano opuesta a la pierna de apoyo',
      'Apóyate suavemente si lo necesitas',
      'Lleva la cadera atrás manteniendo la espalda larga',
      'Desciende hasta donde controles',
      'Vuelve arriba apretando glúteo',
    ],
    variants: [
      { name: 'Contralateral Supported Single-Leg Deadlift' },
      { name: 'Tempo Contralateral Supported Single-Leg Deadlift', descriptionSuffix: 'La bajada lenta mejora el equilibrio y la técnica.' },
      { name: 'Paused Contralateral Supported Single-Leg Deadlift', descriptionSuffix: 'La pausa abajo aumenta la conciencia postural.' },
      { name: 'Alternating Contralateral Supported Single-Leg Deadlift', descriptionSuffix: 'Cambiar de lado continuamente mejora coordinación global.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Marcha supina controlada para integrar abdomen profundo y coordinación de caderas.',
    instructions: [
      'Acuéstate con ambas rodillas elevadas a 90 grados',
      'Mantén la zona lumbar estable',
      'Baja una pierna hacia el suelo y vuelve',
      'Alterna el gesto con la otra pierna',
      'Respira sin perder el control del tronco',
    ],
    variants: [
      { name: 'Supine March' },
      { name: 'Tempo Supine March', descriptionSuffix: 'El ritmo lento aumenta el trabajo de control del core.' },
      { name: 'Paused Supine March', descriptionSuffix: 'La pausa en cada descenso mejora estabilidad pélvica.' },
      { name: 'Alternating Supine March Reach', descriptionSuffix: 'Añadir un alcance de brazos eleva la demanda coordinativa.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Glúteos',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Puente con banda sobre rodillas para glúteo mayor y medio con baja agresividad.',
    instructions: [
      'Acuéstate boca arriba con banda sobre las rodillas',
      'Empuja las rodillas ligeramente hacia afuera',
      'Eleva las caderas activando glúteos',
      'Mantén la apertura de la banda arriba',
      'Desciende lentamente sin perder tensión',
    ],
    variants: [
      { name: 'Banded Glute Bridge' },
      { name: 'Tempo Banded Glute Bridge', descriptionSuffix: 'La bajada lenta mejora control pélvico y sensación de glúteo.' },
      { name: 'Paused Banded Glute Bridge', descriptionSuffix: 'La pausa arriba aumenta activación y estabilidad.' },
      { name: 'Alternating Banded Glute Bridge March', descriptionSuffix: 'La marcha alterna añade reto de core y pelvis.' },
    ],
  },
];

const outdoorTemplates: Template[] = [
  {
    category: 'Cardio',
    muscleGroup: 'Full body',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Intervalos caminando a ritmo vivo, recomendables para mejorar capacidad aeróbica a partir de los 40.',
    instructions: [
      'Camina a ritmo cómodo durante unos minutos para entrar en calor',
      'Aumenta el paso durante el tramo de trabajo',
      'Recupera caminando más despacio',
      'Mantén postura alta y braceo natural',
      'Repite los intervalos según el tiempo planificado',
    ],
    variants: [
      { name: 'Brisk Walk Intervals' },
      { name: 'Tempo Brisk Walk Intervals', descriptionSuffix: 'La progresión de ritmo se hace de forma más gradual y controlada.' },
    ],
  },
  {
    category: 'Cardio',
    muscleGroup: 'Piernas',
    equipment: 'Peso corporal',
    difficulty: 'Intermedio',
    description: 'Caminata en ligera pendiente para mejorar capacidad cardiovascular y fuerza de piernas con bajo impacto.',
    instructions: [
      'Busca una pendiente suave y segura',
      'Camina con zancada corta y tronco erguido',
      'Mantén un ritmo que permita respirar con control',
      'Desciende despacio para recuperar',
      'Repite los bloques de trabajo marcados',
    ],
    variants: [
      { name: 'Hill Walk Intervals' },
      { name: 'Tempo Hill Walk Intervals', descriptionSuffix: 'La subida se controla más para priorizar estabilidad y técnica.' },
    ],
  },
  {
    category: 'Cardio',
    muscleGroup: 'Piernas',
    equipment: 'Escaleras',
    difficulty: 'Intermedio',
    description: 'Subida de escaleras con intensidad moderada para cardio y fuerza de piernas.',
    instructions: [
      'Usa un tramo de escaleras estable y seguro',
      'Sube a ritmo continuo manteniendo el pecho alto',
      'Apoya toda la planta del pie cuando sea posible',
      'Baja caminando con control',
      'Repite el número de bloques previsto',
    ],
    variants: [
      { name: 'Stair Climb Intervals' },
      { name: 'Tempo Stair Climb Intervals', descriptionSuffix: 'La cadencia se modera para priorizar control de rodilla y tobillo.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Piernas',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Sentarse y levantarse usando un banco de parque como apoyo funcional al aire libre.',
    instructions: [
      'Colócate delante de un banco estable',
      'Siéntate con control sin dejarte caer',
      'Apoya bien los pies y elévate de nuevo',
      'Mantén el pecho alto durante todo el gesto',
      'Controla especialmente la bajada',
    ],
    variants: [
      { name: 'Park Bench Sit-to-Stand' },
      { name: 'Tempo Park Bench Sit-to-Stand', descriptionSuffix: 'La bajada lenta mejora fuerza funcional y control.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Pecho',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Flexión inclinada sobre banco de parque para entrenar tren superior con baja carga relativa.',
    instructions: [
      'Apoya las manos en un banco o barandilla estable',
      'Camina con los pies atrás hasta alinear el cuerpo',
      'Desciende el pecho con control',
      'Empuja de nuevo hasta extender los brazos',
      'Mantén abdomen y glúteos activos',
    ],
    variants: [
      { name: 'Park Bench Incline Push-ups' },
      { name: 'Tempo Park Bench Incline Push-ups', descriptionSuffix: 'El descenso más lento prioriza técnica y estabilidad del hombro.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Espalda',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Remo con banda anclada en poste o soporte seguro de parque para espalda y postura.',
    instructions: [
      'Ancla la banda a un poste estable a la altura del ombligo',
      'Retrocede hasta notar tensión',
      'Tira de los codos hacia atrás manteniendo el pecho abierto',
      'Aprieta escápulas al final',
      'Regresa lentamente a la posición inicial',
    ],
    variants: [
      { name: 'Outdoor Resistance Band Row' },
      { name: 'Tempo Outdoor Resistance Band Row', descriptionSuffix: 'La vuelta lenta mejora el control postural y escapular.' },
    ],
  },
  {
    category: 'Fuerza',
    muscleGroup: 'Pecho',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Press de pecho con banda anclada en un soporte exterior para entrenar el empuje al aire libre.',
    instructions: [
      'Ancla la banda detrás del cuerpo en un soporte estable',
      'Sujeta los extremos a la altura del pecho',
      'Empuja las manos al frente sin elevar los hombros',
      'Mantén el tronco firme y estable',
      'Vuelve con control a la posición inicial',
    ],
    variants: [
      { name: 'Outdoor Resistance Band Chest Press' },
      { name: 'Tempo Outdoor Resistance Band Chest Press', descriptionSuffix: 'La vuelta lenta aumenta control y tiempo bajo tensión.' },
    ],
  },
  {
    category: 'Core',
    muscleGroup: 'Core',
    equipment: 'Banda elástica',
    difficulty: 'Principiante',
    description: 'Pallof press con paso al aire libre para estabilidad del tronco y control antirotacional.',
    instructions: [
      'Ancla la banda a un poste estable',
      'Colócate perpendicular al anclaje y sujeta la banda al pecho',
      'Extiende los brazos sin girarte',
      'Da un pequeño paso alejándote del poste',
      'Vuelve con control manteniendo el abdomen activo',
    ],
    variants: [
      { name: 'Outdoor Pallof Press Walkout' },
      { name: 'Tempo Outdoor Pallof Press Walkout', descriptionSuffix: 'Los pasos lentos y controlados refuerzan la estabilidad global.' },
    ],
  },
  {
    category: 'Cardio',
    muscleGroup: 'Full body',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Marcha activa con rodillas altas, útil para elevar pulsaciones sin impacto excesivo.',
    instructions: [
      'Camina elevando las rodillas más de lo habitual',
      'Mantén el tronco erguido y el braceo activo',
      'Apoya el pie con suavidad al descender',
      'Sostén un ritmo que puedas controlar',
      'Recupera caminando normal entre bloques',
    ],
    variants: [
      { name: 'Marching High Knees Walk' },
      { name: 'Tempo Marching High Knees Walk', descriptionSuffix: 'La versión más lenta enfatiza equilibrio y coordinación.' },
    ],
  },
  {
    category: 'Cardio',
    muscleGroup: 'Full body',
    equipment: 'Peso corporal',
    difficulty: 'Principiante',
    description: 'Paso lateral amplio y suave para trabajo cardiovascular de bajo impacto al aire libre.',
    instructions: [
      'Da un paso lateral amplio y lleva el otro pie a juntarse',
      'Alterna la dirección en cada repetición',
      'Mantén rodillas y caderas ligeramente flexionadas',
      'Coordina el braceo con el desplazamiento',
      'Sostén un ritmo continuo y cómodo',
    ],
    variants: [
      { name: 'Low Impact Skater Step' },
      { name: 'Tempo Low Impact Skater Step', descriptionSuffix: 'El ritmo más controlado mejora equilibrio y estabilidad lateral.' },
    ],
  },
  {
    category: 'Balance',
    muscleGroup: 'Full body',
    equipment: 'Mancuernas',
    difficulty: 'Intermedio',
    description: 'Marcha o desplazamiento corto con mancuernas al aire libre para postura, agarre y estabilidad total.',
    instructions: [
      'Sujeta una mancuerna en cada mano o una sola según nivel',
      'Camina despacio manteniendo el torso erguido',
      'Controla la respiración y el balanceo del cuerpo',
      'Da pasos cortos y estables',
      'Descansa y repite los bloques marcados',
    ],
    variants: [
      { name: 'Outdoor Farmer Carry March' },
      { name: 'Tempo Outdoor Farmer Carry March', descriptionSuffix: 'La marcha lenta prioriza equilibrio, agarre y control del tronco.' },
    ],
  },
];

export const expandedHomeOutdoorExercises = [
  ...buildExercises(homeTemplates),
  ...buildExercises(outdoorTemplates),
];
