export interface SeedRecipeIngredient {
  name: string;
  quantity: number;
  unit: string;
}

export interface SeedRecipe {
  name: string;
  description: string;
  instructions: string[];
  prepTime: number;
  cookTime: number;
  servings: number;
  difficulty: 'facil' | 'medio' | 'dificil';
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  tags: string[];
  mealTypes: string[];
  dietTypes: string[];
  goalTypes: string[];
  ingredients: SeedRecipeIngredient[];
}

export const SYSTEM_RECIPES: SeedRecipe[] = [
  {
    name: 'Tostadas mediterráneas con tomate y huevo',
    description: 'Desayuno de inspiración mediterránea con pan integral, tomate rallado, aceite de oliva virgen extra y huevo para mejorar saciedad.',
    instructions: [
      'Tostar el pan integral hasta que quede dorado.',
      'Rallar el tomate y mezclarlo con aceite de oliva y una pizca de sal.',
      'Cocinar los huevos a la plancha o pochados.',
      'Montar las tostadas con tomate, huevo y orégano antes de servir.',
    ],
    prepTime: 8,
    cookTime: 6,
    servings: 1,
    difficulty: 'facil',
    calories: 390,
    protein: 20,
    carbs: 29,
    fat: 20,
    fiber: 5,
    tags: ['desayuno', 'mediterranea', 'saciante'],
    mealTypes: ['desayuno'],
    dietTypes: ['mediterranea'],
    goalTypes: ['mantenimiento', 'perdida_peso'],
    ingredients: [
      { name: 'pan integral', quantity: 2, unit: 'rebanada' },
      { name: 'tomate', quantity: 120, unit: 'g' },
      { name: 'huevo', quantity: 2, unit: 'unidad' },
      { name: 'aceite de oliva virgen extra', quantity: 10, unit: 'ml' },
      { name: 'oregano', quantity: 1, unit: 'g' },
    ],
  },
  {
    name: 'Yogur griego con avena, nueces y frutos rojos',
    description: 'Bol frío con buen perfil de grasa saludable y fibra, útil para desayunos rápidos o meriendas completas.',
    instructions: [
      'Servir el yogur griego en un bol amplio.',
      'Añadir la avena y mezclar para que tome textura cremosa.',
      'Coronar con frutos rojos, nueces troceadas y canela.',
      'Consumir de inmediato o dejar 10 minutos para una textura más densa.',
    ],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: 'facil',
    calories: 420,
    protein: 24,
    carbs: 35,
    fat: 19,
    fiber: 6,
    tags: ['desayuno', 'mediterranea', 'snack'],
    mealTypes: ['desayuno', 'snack'],
    dietTypes: ['mediterranea', 'alta_proteina'],
    goalTypes: ['mantenimiento', 'ganancia_muscular'],
    ingredients: [
      { name: 'yogur griego natural', quantity: 220, unit: 'g' },
      { name: 'avena', quantity: 40, unit: 'g' },
      { name: 'nueces', quantity: 20, unit: 'g' },
      { name: 'frutos rojos', quantity: 80, unit: 'g' },
      { name: 'canela', quantity: 1, unit: 'g' },
    ],
  },
  {
    name: 'Ensalada de garbanzos, atún y pepino',
    description: 'Comida fría fácil de preparar con legumbre, proteína marina y aceite de oliva como base del patrón mediterráneo.',
    instructions: [
      'Lavar y escurrir bien los garbanzos cocidos.',
      'Trocear pepino, tomate y cebolla morada en cubos pequeños.',
      'Mezclar con el atún desmigado y los garbanzos.',
      'Aliñar con aceite de oliva, limón y perejil picado.',
    ],
    prepTime: 12,
    cookTime: 0,
    servings: 1,
    difficulty: 'facil',
    calories: 510,
    protein: 35,
    carbs: 38,
    fat: 22,
    fiber: 10,
    tags: ['almuerzo', 'mediterranea', 'legumbres'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['mediterranea'],
    goalTypes: ['mantenimiento', 'perdida_peso'],
    ingredients: [
      { name: 'garbanzos cocidos', quantity: 180, unit: 'g' },
      { name: 'atun al natural', quantity: 120, unit: 'g' },
      { name: 'pepino', quantity: 100, unit: 'g' },
      { name: 'tomate', quantity: 120, unit: 'g' },
      { name: 'cebolla morada', quantity: 40, unit: 'g' },
      { name: 'aceite de oliva virgen extra', quantity: 12, unit: 'ml' },
      { name: 'limon', quantity: 20, unit: 'ml' },
    ],
  },
  {
    name: 'Salmón al horno con boniato y espárragos',
    description: 'Cena mediterránea rica en omega-3, con carbohidrato complejo y verdura para un plato completo.',
    instructions: [
      'Precalentar el horno a 200 grados.',
      'Cortar el boniato en cubos, mezclar con aceite y hornear 15 minutos.',
      'Añadir salmón y espárragos a la bandeja y hornear 12 minutos más.',
      'Servir con limón y eneldo.',
    ],
    prepTime: 10,
    cookTime: 27,
    servings: 1,
    difficulty: 'medio',
    calories: 590,
    protein: 37,
    carbs: 33,
    fat: 31,
    fiber: 7,
    tags: ['cena', 'mediterranea', 'omega3'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['mediterranea'],
    goalTypes: ['mantenimiento', 'ganancia_muscular'],
    ingredients: [
      { name: 'salmon', quantity: 180, unit: 'g' },
      { name: 'boniato', quantity: 180, unit: 'g' },
      { name: 'esparragos verdes', quantity: 120, unit: 'g' },
      { name: 'aceite de oliva virgen extra', quantity: 12, unit: 'ml' },
      { name: 'limon', quantity: 20, unit: 'ml' },
      { name: 'eneldo', quantity: 2, unit: 'g' },
    ],
  },
  {
    name: 'Pasta integral con pollo, espinacas y aceitunas',
    description: 'Plato templado con pasta integral, pollo y verduras, pensado para días de mayor demanda energética.',
    instructions: [
      'Cocer la pasta integral siguiendo las instrucciones del fabricante.',
      'Saltear el pollo en tiras con ajo y aceite hasta dorar.',
      'Añadir espinacas y aceitunas, y cocinar 2 minutos más.',
      'Incorporar la pasta, mezclar y terminar con pimienta negra.',
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 1,
    difficulty: 'medio',
    calories: 630,
    protein: 42,
    carbs: 58,
    fat: 23,
    fiber: 9,
    tags: ['almuerzo', 'mediterranea', 'pasta'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['mediterranea'],
    goalTypes: ['ganancia_muscular', 'mantenimiento'],
    ingredients: [
      { name: 'pasta integral', quantity: 85, unit: 'g' },
      { name: 'pechuga de pollo', quantity: 160, unit: 'g' },
      { name: 'espinaca fresca', quantity: 80, unit: 'g' },
      { name: 'aceitunas', quantity: 30, unit: 'g' },
      { name: 'ajo', quantity: 1, unit: 'unidad' },
      { name: 'aceite de oliva virgen extra', quantity: 10, unit: 'ml' },
    ],
  },
  {
    name: 'Crema de lentejas rojas con yogur y menta',
    description: 'Crema vegetal densa y reconfortante con buena carga de fibra y proteína vegetal.',
    instructions: [
      'Sofreír cebolla y zanahoria con aceite hasta ablandar.',
      'Añadir lentejas rojas, caldo y comino, y cocer 18 minutos.',
      'Triturar hasta obtener una textura fina.',
      'Servir con una cucharada de yogur y menta picada.',
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    difficulty: 'facil',
    calories: 340,
    protein: 18,
    carbs: 39,
    fat: 11,
    fiber: 11,
    tags: ['cena', 'mediterranea', 'legumbres'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['mediterranea', 'dash'],
    goalTypes: ['perdida_peso', 'mantenimiento'],
    ingredients: [
      { name: 'lenteja roja', quantity: 140, unit: 'g' },
      { name: 'cebolla', quantity: 80, unit: 'g' },
      { name: 'zanahoria', quantity: 80, unit: 'g' },
      { name: 'caldo de verduras bajo en sodio', quantity: 700, unit: 'ml' },
      { name: 'aceite de oliva virgen extra', quantity: 10, unit: 'ml' },
      { name: 'yogur natural', quantity: 40, unit: 'g' },
      { name: 'menta fresca', quantity: 4, unit: 'g' },
    ],
  },
  {
    name: 'Avena cremosa con plátano y semillas',
    description: 'Desayuno suave y alto en potasio con avena, leche y semillas para el enfoque DASH.',
    instructions: [
      'Calentar la leche con la avena a fuego medio hasta espesar.',
      'Añadir canela y remover durante 5 minutos.',
      'Servir con plátano en rodajas y semillas por encima.',
    ],
    prepTime: 5,
    cookTime: 6,
    servings: 1,
    difficulty: 'facil',
    calories: 360,
    protein: 15,
    carbs: 51,
    fat: 11,
    fiber: 8,
    tags: ['desayuno', 'dash', 'avena'],
    mealTypes: ['desayuno'],
    dietTypes: ['dash'],
    goalTypes: ['mantenimiento', 'perdida_peso'],
    ingredients: [
      { name: 'avena', quantity: 55, unit: 'g' },
      { name: 'leche semidesnatada', quantity: 220, unit: 'ml' },
      { name: 'platano', quantity: 100, unit: 'g' },
      { name: 'semillas de chia', quantity: 10, unit: 'g' },
      { name: 'canela', quantity: 1, unit: 'g' },
    ],
  },
  {
    name: 'Tortilla de claras con espinacas y champiñones',
    description: 'Desayuno ligero en sodio y rico en proteína, útil para control de apetito y adherencia.',
    instructions: [
      'Saltear champiñones y espinacas en una sartén antiadherente.',
      'Batir claras con el huevo entero y verter sobre la sartén.',
      'Cuajar a fuego medio y doblar la tortilla antes de servir.',
    ],
    prepTime: 8,
    cookTime: 7,
    servings: 1,
    difficulty: 'facil',
    calories: 290,
    protein: 28,
    carbs: 7,
    fat: 14,
    fiber: 3,
    tags: ['desayuno', 'dash', 'proteico'],
    mealTypes: ['desayuno'],
    dietTypes: ['dash', 'alta_proteina'],
    goalTypes: ['perdida_peso', 'mantenimiento'],
    ingredients: [
      { name: 'claras de huevo', quantity: 180, unit: 'g' },
      { name: 'huevo', quantity: 1, unit: 'unidad' },
      { name: 'espinaca fresca', quantity: 60, unit: 'g' },
      { name: 'champiñon', quantity: 80, unit: 'g' },
      { name: 'aceite de oliva virgen extra', quantity: 5, unit: 'ml' },
    ],
  },
  {
    name: 'Bowl DASH de arroz integral, pavo y brócoli',
    description: 'Comida equilibrada con proteína magra, cereal integral y verdura alta en micronutrientes.',
    instructions: [
      'Cocer el arroz integral hasta que quede tierno.',
      'Cocinar el pavo a la plancha con pimienta, ajo y zumo de limón.',
      'Cocer o saltear el brócoli y montar el bowl con tomate y perejil.',
    ],
    prepTime: 10,
    cookTime: 22,
    servings: 1,
    difficulty: 'medio',
    calories: 560,
    protein: 39,
    carbs: 54,
    fat: 17,
    fiber: 8,
    tags: ['almuerzo', 'dash', 'batch'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['dash'],
    goalTypes: ['mantenimiento', 'ganancia_muscular'],
    ingredients: [
      { name: 'arroz integral', quantity: 80, unit: 'g' },
      { name: 'pechuga de pavo', quantity: 170, unit: 'g' },
      { name: 'brocoli', quantity: 140, unit: 'g' },
      { name: 'tomate', quantity: 100, unit: 'g' },
      { name: 'aceite de oliva virgen extra', quantity: 10, unit: 'ml' },
      { name: 'limon', quantity: 15, unit: 'ml' },
    ],
  },
  {
    name: 'Merluza con puré de coliflor y judías verdes',
    description: 'Cena baja en sodio y ligera, muy apta para digestiones fáciles sin renunciar a proteína.',
    instructions: [
      'Cocer la coliflor y triturarla con yogur natural hasta formar un puré.',
      'Cocinar la merluza a la plancha con ajo y pimienta.',
      'Hervir las judías verdes y servir junto al pescado y el puré.',
    ],
    prepTime: 10,
    cookTime: 18,
    servings: 1,
    difficulty: 'medio',
    calories: 430,
    protein: 39,
    carbs: 18,
    fat: 20,
    fiber: 7,
    tags: ['cena', 'dash', 'pescado blanco'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['dash'],
    goalTypes: ['perdida_peso', 'mantenimiento'],
    ingredients: [
      { name: 'merluza', quantity: 180, unit: 'g' },
      { name: 'coliflor', quantity: 220, unit: 'g' },
      { name: 'judias verdes', quantity: 140, unit: 'g' },
      { name: 'yogur natural', quantity: 40, unit: 'g' },
      { name: 'ajo', quantity: 1, unit: 'unidad' },
      { name: 'aceite de oliva virgen extra', quantity: 10, unit: 'ml' },
    ],
  },
  {
    name: 'Wrap integral de hummus, pollo y verduras',
    description: 'Almuerzo portátil con buen reparto de macros y sodio controlado si se prepara en casa.',
    instructions: [
      'Calentar ligeramente la tortilla integral.',
      'Untar hummus en toda la superficie.',
      'Añadir pollo cocinado, zanahoria, lechuga y pepino en tiras.',
      'Enrollar con firmeza y cortar por la mitad.',
    ],
    prepTime: 12,
    cookTime: 5,
    servings: 1,
    difficulty: 'facil',
    calories: 490,
    protein: 33,
    carbs: 40,
    fat: 20,
    fiber: 8,
    tags: ['almuerzo', 'dash', 'portable'],
    mealTypes: ['almuerzo'],
    dietTypes: ['dash', 'mediterranea'],
    goalTypes: ['mantenimiento', 'perdida_peso'],
    ingredients: [
      { name: 'tortilla integral', quantity: 1, unit: 'unidad' },
      { name: 'hummus', quantity: 45, unit: 'g' },
      { name: 'pechuga de pollo', quantity: 130, unit: 'g' },
      { name: 'lechuga', quantity: 40, unit: 'g' },
      { name: 'pepino', quantity: 60, unit: 'g' },
      { name: 'zanahoria', quantity: 50, unit: 'g' },
    ],
  },
  {
    name: 'Bowl de yogur con kiwi y almendras',
    description: 'Snack o desayuno ligero rico en calcio, potasio y grasas insaturadas.',
    instructions: [
      'Servir el yogur en un bol.',
      'Añadir el kiwi troceado y las almendras laminadas.',
      'Terminar con copos de avena si se desea más saciedad.',
    ],
    prepTime: 4,
    cookTime: 0,
    servings: 1,
    difficulty: 'facil',
    calories: 250,
    protein: 16,
    carbs: 19,
    fat: 11,
    fiber: 4,
    tags: ['snack', 'dash', 'calcio'],
    mealTypes: ['desayuno', 'snack'],
    dietTypes: ['dash'],
    goalTypes: ['mantenimiento', 'perdida_peso'],
    ingredients: [
      { name: 'yogur natural', quantity: 170, unit: 'g' },
      { name: 'kiwi', quantity: 80, unit: 'g' },
      { name: 'almendra', quantity: 15, unit: 'g' },
      { name: 'copos de avena', quantity: 10, unit: 'g' },
    ],
  },
  {
    name: 'Ensalada potente de pollo, aguacate y huevo',
    description: 'Comida principal apta para ventana de alimentación 16:8, alta en saciedad y proteína.',
    instructions: [
      'Cocinar el pollo a la plancha y cortarlo en tiras.',
      'Cocer el huevo durante 8 minutos y pelarlo.',
      'Montar la ensalada con hojas verdes, tomate, aguacate y pollo.',
      'Aliñar con aceite de oliva y limón.',
    ],
    prepTime: 12,
    cookTime: 10,
    servings: 1,
    difficulty: 'facil',
    calories: 610,
    protein: 46,
    carbs: 14,
    fat: 39,
    fiber: 8,
    tags: ['almuerzo', 'ayuno_intermitente', 'saciante'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['ayuno_intermitente', 'alta_proteina'],
    goalTypes: ['perdida_peso', 'mantenimiento'],
    ingredients: [
      { name: 'pechuga de pollo', quantity: 180, unit: 'g' },
      { name: 'aguacate', quantity: 90, unit: 'g' },
      { name: 'huevo', quantity: 1, unit: 'unidad' },
      { name: 'mezcla de hojas verdes', quantity: 80, unit: 'g' },
      { name: 'tomate', quantity: 100, unit: 'g' },
      { name: 'aceite de oliva virgen extra', quantity: 10, unit: 'ml' },
    ],
  },
  {
    name: 'Ternera salteada con verduras y arroz de coliflor',
    description: 'Plato bajo en carbohidrato neto, interesante para ayuno intermitente con foco en proteína y saciedad.',
    instructions: [
      'Picar la coliflor hasta obtener textura de arroz y saltear 5 minutos.',
      'Saltear la ternera con ajo y jengibre hasta dorar.',
      'Añadir pimiento, calabacín y salsa de soja baja en sodio.',
      'Servir sobre el arroz de coliflor.',
    ],
    prepTime: 12,
    cookTime: 14,
    servings: 1,
    difficulty: 'medio',
    calories: 540,
    protein: 41,
    carbs: 17,
    fat: 31,
    fiber: 7,
    tags: ['cena', 'ayuno_intermitente', 'low_carb'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['ayuno_intermitente', 'alta_proteina'],
    goalTypes: ['perdida_peso', 'mantenimiento'],
    ingredients: [
      { name: 'ternera magra', quantity: 170, unit: 'g' },
      { name: 'coliflor', quantity: 220, unit: 'g' },
      { name: 'pimiento rojo', quantity: 80, unit: 'g' },
      { name: 'calabacin', quantity: 100, unit: 'g' },
      { name: 'ajo', quantity: 1, unit: 'unidad' },
      { name: 'jengibre fresco', quantity: 5, unit: 'g' },
      { name: 'salsa de soja baja en sodio', quantity: 10, unit: 'ml' },
    ],
  },
  {
    name: 'Salmón con quinoa y espinacas salteadas',
    description: 'Comida densa para ventana 16:8 con omega-3, proteína y carbohidrato complejo en ración controlada.',
    instructions: [
      'Cocer la quinoa hasta que quede suelta.',
      'Marcar el salmón a la plancha o en horno hasta su punto.',
      'Saltear espinacas con ajo y aceite durante 2 minutos.',
      'Servir junto con limón y pimienta.',
    ],
    prepTime: 10,
    cookTime: 18,
    servings: 1,
    difficulty: 'medio',
    calories: 620,
    protein: 39,
    carbs: 34,
    fat: 34,
    fiber: 6,
    tags: ['almuerzo', 'ayuno_intermitente', 'omega3'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['ayuno_intermitente', 'mediterranea'],
    goalTypes: ['mantenimiento', 'ganancia_muscular'],
    ingredients: [
      { name: 'salmon', quantity: 180, unit: 'g' },
      { name: 'quinoa', quantity: 70, unit: 'g' },
      { name: 'espinaca fresca', quantity: 90, unit: 'g' },
      { name: 'ajo', quantity: 1, unit: 'unidad' },
      { name: 'aceite de oliva virgen extra', quantity: 10, unit: 'ml' },
      { name: 'limon', quantity: 15, unit: 'ml' },
    ],
  },
  {
    name: 'Tortilla de patata ligera con ensalada crujiente',
    description: 'Versión controlada de tortilla española para una comida principal de ayuno intermitente.',
    instructions: [
      'Cocinar la patata en microondas o al vapor hasta ablandar.',
      'Pochar la cebolla con poco aceite.',
      'Mezclar con los huevos batidos y cuajar la tortilla a fuego medio.',
      'Servir con ensalada de hojas verdes y pepino.',
    ],
    prepTime: 12,
    cookTime: 16,
    servings: 1,
    difficulty: 'medio',
    calories: 520,
    protein: 24,
    carbs: 34,
    fat: 30,
    fiber: 5,
    tags: ['cena', 'ayuno_intermitente', 'tradicional'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['ayuno_intermitente', 'mediterranea'],
    goalTypes: ['mantenimiento'],
    ingredients: [
      { name: 'patata', quantity: 180, unit: 'g' },
      { name: 'huevo', quantity: 3, unit: 'unidad' },
      { name: 'cebolla', quantity: 70, unit: 'g' },
      { name: 'mezcla de hojas verdes', quantity: 60, unit: 'g' },
      { name: 'pepino', quantity: 60, unit: 'g' },
      { name: 'aceite de oliva virgen extra', quantity: 12, unit: 'ml' },
    ],
  },
  {
    name: 'Pavo con hummus, crudités y pan pita integral',
    description: 'Comida práctica de ventana 16:8, rica en proteína y fácil de llevar.',
    instructions: [
      'Cortar el pavo en tiras si no viene loncheado.',
      'Preparar bastones de zanahoria y pepino.',
      'Servir con hummus y pan pita integral calentado.',
    ],
    prepTime: 8,
    cookTime: 2,
    servings: 1,
    difficulty: 'facil',
    calories: 500,
    protein: 34,
    carbs: 43,
    fat: 20,
    fiber: 8,
    tags: ['almuerzo', 'ayuno_intermitente', 'portable'],
    mealTypes: ['almuerzo'],
    dietTypes: ['ayuno_intermitente', 'dash'],
    goalTypes: ['mantenimiento', 'perdida_peso'],
    ingredients: [
      { name: 'pechuga de pavo', quantity: 150, unit: 'g' },
      { name: 'hummus', quantity: 50, unit: 'g' },
      { name: 'zanahoria', quantity: 70, unit: 'g' },
      { name: 'pepino', quantity: 70, unit: 'g' },
      { name: 'pan pita integral', quantity: 1, unit: 'unidad' },
    ],
  },
  {
    name: 'Pollo al curry suave con arroz basmati',
    description: 'Plato completo para una de las dos comidas del día en ayuno intermitente, con perfil reconfortante y alta adherencia.',
    instructions: [
      'Cocer el arroz basmati y reservar.',
      'Saltear cebolla y pollo con curry suave.',
      'Añadir yogur natural y dejar reducir unos minutos.',
      'Servir con arroz y cilantro fresco.',
    ],
    prepTime: 10,
    cookTime: 18,
    servings: 1,
    difficulty: 'medio',
    calories: 610,
    protein: 43,
    carbs: 55,
    fat: 23,
    fiber: 4,
    tags: ['cena', 'ayuno_intermitente', 'comfort'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['ayuno_intermitente'],
    goalTypes: ['mantenimiento', 'ganancia_muscular'],
    ingredients: [
      { name: 'pechuga de pollo', quantity: 180, unit: 'g' },
      { name: 'arroz basmati', quantity: 80, unit: 'g' },
      { name: 'cebolla', quantity: 60, unit: 'g' },
      { name: 'yogur natural', quantity: 60, unit: 'g' },
      { name: 'curry suave', quantity: 4, unit: 'g' },
      { name: 'cilantro fresco', quantity: 3, unit: 'g' },
    ],
  },
  {
    name: 'Porridge proteico de vainilla y frutos rojos',
    description: 'Desayuno con proteína añadida y textura cremosa para empezar el día con saciedad.',
    instructions: [
      'Cocer la avena con leche o bebida vegetal hasta espesar.',
      'Retirar del fuego y mezclar con proteína en polvo de vainilla.',
      'Servir con frutos rojos y semillas de chía.',
    ],
    prepTime: 5,
    cookTime: 6,
    servings: 1,
    difficulty: 'facil',
    calories: 430,
    protein: 32,
    carbs: 38,
    fat: 14,
    fiber: 7,
    tags: ['desayuno', 'alta_proteina', 'avena'],
    mealTypes: ['desayuno'],
    dietTypes: ['alta_proteina'],
    goalTypes: ['ganancia_muscular', 'mantenimiento'],
    ingredients: [
      { name: 'avena', quantity: 50, unit: 'g' },
      { name: 'leche semidesnatada', quantity: 220, unit: 'ml' },
      { name: 'proteina de vainilla', quantity: 30, unit: 'g' },
      { name: 'frutos rojos', quantity: 70, unit: 'g' },
      { name: 'semillas de chia', quantity: 10, unit: 'g' },
    ],
  },
  {
    name: 'Tostada de requesón, salmón ahumado y pepino',
    description: 'Desayuno o snack proteico con perfil salado y preparación muy rápida.',
    instructions: [
      'Tostar el pan integral.',
      'Untar el requesón sobre la tostada.',
      'Añadir salmón ahumado, pepino laminado y eneldo.',
    ],
    prepTime: 6,
    cookTime: 2,
    servings: 1,
    difficulty: 'facil',
    calories: 340,
    protein: 26,
    carbs: 24,
    fat: 14,
    fiber: 4,
    tags: ['desayuno', 'alta_proteina', 'snack'],
    mealTypes: ['desayuno', 'snack'],
    dietTypes: ['alta_proteina'],
    goalTypes: ['mantenimiento', 'ganancia_muscular'],
    ingredients: [
      { name: 'pan integral', quantity: 2, unit: 'rebanada' },
      { name: 'requeson', quantity: 80, unit: 'g' },
      { name: 'salmon ahumado', quantity: 60, unit: 'g' },
      { name: 'pepino', quantity: 50, unit: 'g' },
      { name: 'eneldo', quantity: 2, unit: 'g' },
    ],
  },
  {
    name: 'Bowl de pollo, arroz jazmín y edamame',
    description: 'Comida alta en proteína para días de entrenamiento con un perfil de macros fácil de ajustar.',
    instructions: [
      'Cocer el arroz jazmín y el edamame por separado.',
      'Cocinar el pollo a la plancha con ajo y pimentón.',
      'Montar el bowl con zanahoria rallada y sésamo.',
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 1,
    difficulty: 'medio',
    calories: 640,
    protein: 48,
    carbs: 57,
    fat: 21,
    fiber: 8,
    tags: ['almuerzo', 'alta_proteina', 'batch'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['alta_proteina'],
    goalTypes: ['ganancia_muscular', 'mantenimiento'],
    ingredients: [
      { name: 'pechuga de pollo', quantity: 190, unit: 'g' },
      { name: 'arroz jazmin', quantity: 80, unit: 'g' },
      { name: 'edamame', quantity: 90, unit: 'g' },
      { name: 'zanahoria', quantity: 60, unit: 'g' },
      { name: 'semillas de sesamo', quantity: 6, unit: 'g' },
    ],
  },
  {
    name: 'Albóndigas de pavo con calabacín y tomate',
    description: 'Cena rica en proteína con salsa casera ligera y mucha verdura.',
    instructions: [
      'Formar albóndigas con el pavo picado, ajo y perejil.',
      'Dorarlas en sartén con una cucharadita de aceite.',
      'Añadir tomate triturado y calabacín en medias lunas.',
      'Cocinar tapado hasta que todo quede tierno.',
    ],
    prepTime: 12,
    cookTime: 18,
    servings: 1,
    difficulty: 'medio',
    calories: 470,
    protein: 41,
    carbs: 17,
    fat: 25,
    fiber: 6,
    tags: ['cena', 'alta_proteina', 'sin_exceso_carbo'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['alta_proteina'],
    goalTypes: ['perdida_peso', 'ganancia_muscular'],
    ingredients: [
      { name: 'pavo picado', quantity: 180, unit: 'g' },
      { name: 'calabacin', quantity: 180, unit: 'g' },
      { name: 'tomate triturado', quantity: 160, unit: 'g' },
      { name: 'ajo', quantity: 1, unit: 'unidad' },
      { name: 'perejil', quantity: 4, unit: 'g' },
      { name: 'aceite de oliva virgen extra', quantity: 8, unit: 'ml' },
    ],
  },
  {
    name: 'Tacos de ternera magra con yogur y col lombarda',
    description: 'Plato muy adherente con proteína alta y toppings frescos para comidas principales.',
    instructions: [
      'Cocinar la ternera con pimentón, comino y ajo.',
      'Calentar las tortillas de maíz.',
      'Montar con col lombarda, yogur natural y cilantro.',
    ],
    prepTime: 10,
    cookTime: 12,
    servings: 2,
    difficulty: 'facil',
    calories: 520,
    protein: 36,
    carbs: 34,
    fat: 26,
    fiber: 5,
    tags: ['almuerzo', 'alta_proteina', 'adhesion'],
    mealTypes: ['almuerzo', 'cena'],
    dietTypes: ['alta_proteina'],
    goalTypes: ['mantenimiento', 'ganancia_muscular'],
    ingredients: [
      { name: 'ternera magra', quantity: 180, unit: 'g' },
      { name: 'tortilla de maiz', quantity: 4, unit: 'unidad' },
      { name: 'col lombarda', quantity: 80, unit: 'g' },
      { name: 'yogur natural', quantity: 60, unit: 'g' },
      { name: 'cilantro fresco', quantity: 3, unit: 'g' },
    ],
  },
  {
    name: 'Skyr con cacao, plátano y crema de cacahuete',
    description: 'Snack de recuperación con proteína láctea, algo de carbohidrato y sabor dulce controlado.',
    instructions: [
      'Servir el skyr en un cuenco.',
      'Mezclar con cacao puro hasta integrar.',
      'Añadir plátano en rodajas y crema de cacahuete por encima.',
    ],
    prepTime: 4,
    cookTime: 0,
    servings: 1,
    difficulty: 'facil',
    calories: 300,
    protein: 24,
    carbs: 24,
    fat: 11,
    fiber: 4,
    tags: ['snack', 'alta_proteina', 'postentreno'],
    mealTypes: ['snack'],
    dietTypes: ['alta_proteina'],
    goalTypes: ['ganancia_muscular', 'mantenimiento'],
    ingredients: [
      { name: 'skyr natural', quantity: 180, unit: 'g' },
      { name: 'cacao puro', quantity: 5, unit: 'g' },
      { name: 'platano', quantity: 70, unit: 'g' },
      { name: 'crema de cacahuete', quantity: 12, unit: 'g' },
    ],
  },
];
